In [1]:
import pandas as pd

In [18]:
# Read a sample of the data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
df = pd.read_csv(prefix + 'yellow_tripdata_2021-01.csv.gz', nrows=100)

In [19]:
# Display first rows
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [20]:
# Check the data types
df.dtypes

VendorID                   int64
tpep_pickup_datetime         str
tpep_dropoff_datetime        str
passenger_count            int64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag           str
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [21]:
# Check the data shape
df.shape

(100, 18)

In [25]:
# Type parsing
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

# Date columns
parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

# Read in the full dataset again
df = pd.read_csv(
    prefix + 'yellow_tripdata_2021-01.csv.gz',
    dtype=dtype,
    parse_dates=parse_dates,
    nrows=100
)

In [26]:
# First 10 rows
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
5,1,2021-01-01 00:16:29,2021-01-01 00:24:30,1,1.60,1,N,224,68,1,8.0,3.0,0.5,2.35,0.0,0.3,14.15,2.5
6,1,2021-01-01 00:00:28,2021-01-01 00:17:28,1,4.10,1,N,95,157,2,16.0,0.5,0.5,0.00,0.0,0.3,17.30,0.0
7,1,2021-01-01 00:12:29,2021-01-01 00:30:34,1,5.70,1,N,90,40,2,18.0,3.0,0.5,0.00,0.0,0.3,21.80,2.5
8,1,2021-01-01 00:39:16,2021-01-01 01:00:13,1,9.10,1,N,97,129,4,27.5,0.5,0.5,0.00,0.0,0.3,28.80,0.0
9,1,2021-01-01 00:26:12,2021-01-01 00:39:46,2,2.70,1,N,263,142,1,12.0,3.0,0.5,3.15,0.0,0.3,18.95,2.5

In [27]:
# Data shape
df.shape

(100, 18)

In [28]:
# Create Database Connection
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg://root:root@localhost:5432/ny_taxi')

In [29]:
# Get the DDL Schema
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [30]:
# Create the table
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [35]:
df_iter = pd.read_csv(
    prefix + "yellow_tripdata_2021-01.csv.gz",
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=10000
)

In [36]:
df_iter

In [33]:
for df_chunk in df_iter:
    print(len(df_chunk))

50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
50000
19765

In [37]:
from tqdm.auto import tqdm

first = True

for df_chunk in tqdm(df_iter):
    if first:
        # Create a table schema (no data)
        df_chunk.head(0).to_sql(name="yellow_taxi_data", con=engine, if_exists="replace")
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(name="yellow_taxi_data",con=engine,if_exists="append")
    print("Inserted:", len(df_chunk))

0it [00:00, ?it/s]

Table created
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 10000
Inserted: 9765